#%RAML 1.0
title: dbiz-properties-sys-api
description: System api for demo
version: v1

traits:
  client-id-required: !include traits/clientid.raml

/property:
  post:
    is:
      [ client-id-required]
    body:
      application/json:
        example: !include examples/properties.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/properties_response.json


/owners:
  /{propertyId}:
    is:
      [ client-id-required]
    uriParameters:
      propertyId: 
        description: "Property ID"
        required: true
        example: "CH212"
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/owners-response.json

/documents:
  /{propertyId}:
    is:
      [ client-id-required]
    uriParameters:
      propertyId: 
        description: "Property ID"
        required: true
        example: "CH212"
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/documents-response.json

/valuations:
  /{propertyId}:
    is:
      [ client-id-required]
    uriParameters:
      propertyId: 
        description: "Property ID"
        required: true
        example: "CH212"
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/valuations-response.json

/location:
  /{propertyId}:
    is:
      [ client-id-required]
    uriParameters:
      propertyId: 
        description: "Property ID"
        required: true
        example: "CH212"
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/location-response.json
  